# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_initial"),
        ("users", "0002_parent_student_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads_as_parent",
                to="users.user",
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="from_teacher",
        ),
        migrations.AddField(
            model_name="message",
            name="sender_role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                ],
                default="student",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
