# Generated by Django 5.2.6 on 2025-10-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_parent_channels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
