# Generated by Django 5.2.6 on 2025-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push')], max_length=20)),
                ('payload', models.JSONField()),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('read', 'Read')], default='queued', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
