# Generated by Django 5.2.6 on 2025-11-19 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Icon identifier for the frontend', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Achievement categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('resource_view', 'Resource View'), ('assignment_work', 'Assignment Work'), ('voice_practice', 'Voice Practice'), ('quiz_attempt', 'Quiz Attempt'), ('nanu_interaction', 'Nanu Interaction'), ('reward_claim', 'Reward Claim')], max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional activity details', null=True)),
                ('was_successful', models.BooleanField(help_text='Whether the activity was completed successfully', null=True)),
                ('difficulty_reported', models.PositiveSmallIntegerField(blank=True, help_text='Student-reported difficulty (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('needed_help', models.BooleanField(default=False)),
                ('helper_type', models.CharField(blank=True, choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('nanu', 'Nanu Assistant'), ('peer', 'Classmate')], max_length=20)),
                ('voice_notes', models.FileField(blank=True, upload_to='activity/voice/')),
                ('voice_notes_transcript', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completion_type', models.CharField(choices=[('self_marked', 'Self Marked'), ('auto_tracked', 'Automatically Tracked'), ('teacher_verified', 'Teacher Verified')], max_length=20)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken in minutes', null=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('voice_reflection', models.FileField(blank=True, upload_to='completion/voice/')),
                ('reflection_transcript', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('voice_reminder', models.TextField(blank=True, help_text='Custom voice reminder for this schedule')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('voice_announcement', models.TextField(blank=True, help_text='Custom voice announcement for this session')),
            ],
            options={
                'ordering': ['-date', '-actual_start'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
                ('trimester_hint', models.IntegerField(blank=True, null=True)),
                ('has_prereq', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoalReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_recording', models.FileField(blank=True, upload_to='reflections/voice/')),
                ('transcript', models.TextField(blank=True)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('proud', 'Proud'), ('worried', 'Worried'), ('confused', 'Confused'), ('determined', 'Determined')], max_length=20)),
                ('needs_help', models.BooleanField(default=False)),
                ('help_type_requested', models.CharField(blank=True, choices=[('explanation', 'Better Explanation'), ('practice', 'More Practice'), ('different_method', 'Different Learning Method'), ('teacher_help', 'Teacher Help'), ('parent_help', 'Parent Help')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('voice_description', models.TextField(blank=True, help_text='Simple description for TTS')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_revision', 'Needs Revision')], default='not_started', max_length=20)),
                ('parent_notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('voice_description', models.TextField(blank=True, help_text='Simple description for TTS')),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_points', models.PositiveIntegerField(default=0)),
                ('required_attendance', models.PositiveIntegerField(default=0, help_text='Required attendance percentage')),
                ('custom_criteria', models.JSONField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_recording', models.FileField(blank=True, upload_to='milestones/voice/')),
                ('completion_transcript', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['goal', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_type', models.CharField(choices=[('guidance', 'Additional Guidance'), ('resources', 'Extra Resources'), ('practice', 'Practice Session'), ('accommodation', 'Learning Accommodation'), ('intervention', 'Teacher Intervention')], max_length=20)),
                ('description', models.TextField()),
                ('voice_notes', models.FileField(blank=True, upload_to='support/voice/')),
                ('notes_transcript', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_feedback', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LecturerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.IntegerField()),
                ('trimester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('award_level', models.CharField(max_length=50)),
                ('duration_years', models.IntegerField()),
                ('trimesters_per_year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.IntegerField()),
                ('trimester', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_hod', 'Pending HOD Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('reward_description', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.CharField(max_length=20)),
                ('voice_confirmation', models.TextField(blank=True, help_text='Custom voice message when reward is claimed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('day_before', 'Day Before'), ('morning_of', 'Morning Of'), ('hour_before', 'Hour Before')], max_length=20)),
                ('voice_message', models.TextField(blank=True, help_text='Custom voice message for this reminder')),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_earned', models.PositiveIntegerField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.CharField(help_text='Academic term when earned', max_length=20)),
                ('evidence', models.JSONField(blank=True, help_text='Supporting data for the achievement claim', null=True)),
                ('voice_feedback', models.TextField(blank=True, help_text='Custom voice message for this achievement instance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('completion_percentage', models.FloatField(default=0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activity_score', models.FloatField(default=0, help_text='Engagement and activity score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time spent in minutes')),
                ('last_activity_at', models.DateTimeField(null=True)),
                ('consecutive_days', models.PositiveIntegerField(default=0, help_text='Consecutive days of activity')),
                ('latest_voice_feedback', models.FileField(blank=True, upload_to='progress/voice/')),
                ('latest_feedback_transcript', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-term', 'student__user__username'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('content_url', models.URLField()),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('feedback_media_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.IntegerField()),
                ('trimester', models.IntegerField()),
                ('offered', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=20)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('total_points_spent', models.PositiveIntegerField(default=0)),
                ('rewards_claimed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-term'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_recording', models.FileField(blank=True, upload_to='attendance/voice/')),
                ('transcript', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(help_text='Voice recognition confidence (0-1)', null=True)),
                ('location_data', models.JSONField(blank=True, help_text='Optional location verification data', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon identifier for the frontend', max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('max_claims_per_term', models.PositiveIntegerField(default=3, help_text='Maximum times this achievement can be claimed per term')),
                ('requires_approval', models.BooleanField(default=False)),
                ('auto_approve_conditions', models.JSONField(blank=True, help_text='Conditions for automatic approval in JSON format', null=True)),
                ('voice_message', models.TextField(help_text='Encouraging message to speak when achievement is earned')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='learning.achievementcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
