# Generated by Django 5.2.6 on 2025-11-19 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('learning', '0002_initial'),
        ('repository', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_records', to='repository.libraryasset'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='users.student'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.courseschedule'),
        ),
        migrations.AddField(
            model_name='curriculumunit',
            name='prereq_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='users.student'),
        ),
        migrations.AddField(
            model_name='goalreflection',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='learning.learninggoal'),
        ),
        migrations.AddField(
            model_name='learningmilestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='learning.learninggoal'),
        ),
        migrations.AddField(
            model_name='learningmilestone',
            name='required_resources',
            field=models.ManyToManyField(blank=True, related_name='required_for_milestones', to='repository.libraryasset'),
        ),
        migrations.AddField(
            model_name='learningmilestone',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalreflection',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='learning.learningmilestone'),
        ),
        migrations.AddField(
            model_name='learningsupport',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_records', to='learning.learningmilestone'),
        ),
        migrations.AddField(
            model_name='learningsupport',
            name='provided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_support', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsupport',
            name='resources_provided',
            field=models.ManyToManyField(blank=True, related_name='used_in_support', to='repository.libraryasset'),
        ),
        migrations.AddField(
            model_name='lecturerassignment',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='lecturerassignment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='core.department'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='curriculumunit',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_units', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.student'),
        ),
        migrations.AddField(
            model_name='registration',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionreminder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='learning.coursesession'),
        ),
        migrations.AddField(
            model_name='sessionreminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reminders', to='users.student'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='learning.achievement'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.student'),
        ),
        migrations.AddField(
            model_name='termoffering',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.programme'),
        ),
        migrations.AddField(
            model_name='termoffering',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='termprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='term_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.programme'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.curriculumunit'),
        ),
        migrations.AddField(
            model_name='voiceattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_attendance', to='learning.coursesession'),
        ),
        migrations.AddField(
            model_name='voiceattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_attendance', to='users.student'),
        ),
        migrations.AddField(
            model_name='voiceattendance',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lecturerassignment',
            unique_together={('lecturer', 'unit', 'academic_year', 'trimester')},
        ),
        migrations.AlterUniqueTogether(
            name='completionrecord',
            unique_together={('student', 'programme', 'unit', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'unit', 'academic_year', 'trimester')},
        ),
        migrations.AddConstraint(
            model_name='rewardclaim',
            constraint=models.CheckConstraint(condition=models.Q(('points_spent__gt', 0)), name='points_spent_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreminder',
            unique_together={('session', 'student', 'reminder_type')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'programme', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termoffering',
            unique_together={('programme', 'unit', 'academic_year', 'trimester')},
        ),
        migrations.AlterUniqueTogether(
            name='termprogress',
            unique_together={('student', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='voiceattendance',
            unique_together={('student', 'session')},
        ),
    ]
