# Generated by Django 5.2.6 on 2025-10-28 17:32

from django.db import migrations

def backfill(apps, schema_editor):
	Department = apps.get_model('core', 'Department')
	Course = apps.get_model('learning', 'Course')
	dept = Department.objects.order_by('id').first()
	if not dept:
		dept = Department.objects.create(name='General', code='GEN')
	Course.objects.filter(department__isnull=True).update(department=dept)

def reverse_backfill(apps, schema_editor):
	Course = apps.get_model('learning', 'Course')
	Course.objects.update(department=None)

class Migration(migrations.Migration):

	dependencies = [
		('learning', '0004_achievementcategory_alter_course_options_and_more'),
		('core', '0003_department'),
	]

	operations = [
		migrations.RunPython(backfill, reverse_backfill),
	]


