# Generated by Django 5.2.6 on 2025-11-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.programme'),
        ),
    ]
