# Generated by Django 5.2.6 on 2025-11-12 11:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('learning', '0006_assignment_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('trimester', models.PositiveSmallIntegerField(default=1)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('meets_threshold', models.BooleanField(default=False)),
                ('last_payment', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_statuses', to='learning.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'course', 'academic_year', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='FinanceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('trimester', models.PositiveSmallIntegerField(default=1)),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_thresholds', to='learning.course')),
            ],
            options={
                'ordering': ['course_id', 'academic_year', 'trimester'],
                'unique_together': {('course', 'academic_year', 'trimester')},
            },
        ),
    ]
