# Generated by Django 5.2.6 on 2025-11-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('learning', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financestatus',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_statuses', to='users.student'),
        ),
        migrations.AddField(
            model_name='financethreshold',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_thresholds', to='learning.programme'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='financestatus',
            unique_together={('student', 'academic_year', 'trimester')},
        ),
        migrations.AlterUniqueTogether(
            name='financethreshold',
            unique_together={('programme', 'academic_year', 'trimester')},
        ),
    ]
