# Generated by Django 5.2.6 on 2025-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financestatus',
            name='clearance_status',
            field=models.CharField(choices=[('cleared_for_registration', 'Cleared for Registration'), ('cleared_for_exams', 'Cleared for Exams'), ('blocked', 'Blocked')], default='blocked', max_length=30),
        ),
    ]
