# Generated by Django 5.2.6 on 2025-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financestatus_clearance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='trimester',
            field=models.IntegerField(default=0),
        ),
    ]
