# Generated by Django 5.2.6 on 2025-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF'), ('link', 'Link')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
