# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Administrator"),
                    ("hod", "Head of Department"),
                    ("finance", "Finance"),
                    ("records", "Student Records"),
                    ("librarian", "Librarian"),
                ],
                default="student",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ParentStudentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relationship", models.CharField(blank=True, max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_students",
                        to="users.user",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-student link",
                "verbose_name_plural": "Parent-student links",
                "unique_together": {("parent", "student")},
            },
        ),
    ]
