# Generated by Django 5.2.6 on 2025-10-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('lecturer', 'Lecturer'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator'), ('hod', 'Head of Department'), ('finance', 'Finance'), ('records', 'Student Records'), ('librarian', 'Librarian')], default='student', max_length=32),
        ),
    ]
