# Generated by Django 5.2.6 on 2025-10-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprovisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprovisionrequest',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
