# Generated by Django 5.2.6 on 2025-11-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyEnrollmentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('course_codes', models.JSONField(blank=True, default=list)),
                ('student_first_name', models.CharField(blank=True, max_length=150)),
                ('student_last_name', models.CharField(blank=True, max_length=150)),
                ('student_password', models.CharField(blank=True, max_length=128)),
                ('parent_first_name', models.CharField(blank=True, max_length=150)),
                ('parent_last_name', models.CharField(blank=True, max_length=150)),
                ('parent_password', models.CharField(blank=True, max_length=128)),
                ('fee_title', models.CharField(blank=True, max_length=255)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_due_date', models.DateField(blank=True, null=True)),
                ('parent_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_intent_parent', to='users.userprovisionrequest')),
                ('student_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_intent_student', to='users.userprovisionrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
