# Generated by Django 5.2.6 on 2025-11-19 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='users.hod'),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['owner_user', 'start_at'], name='core_calend_owner_u_d99c69_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['source_type', 'source_id'], name='core_calend_source__ca6df0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('owner_user', 'source_type', 'source_id')},
        ),
        migrations.AddIndex(
            model_name='deviceregistration',
            index=models.Index(fields=['user', 'platform'], name='core_device_user_id_b8110e_idx'),
        ),
    ]
