# Generated by Django 5.2.6 on 2025-11-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('timezone_hint', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['owner_user', 'start_at'], name='core_calend_owner_u_d99c69_idx'), models.Index(fields=['source_type', 'source_id'], name='core_calend_source__ca6df0_idx')],
                'unique_together': {('owner_user', 'source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('expo', 'Expo'), ('ios', 'Apple'), ('android', 'Android')], max_length=32)),
                ('push_token', models.CharField(max_length=255, unique=True)),
                ('last_registered_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_registered_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='core_device_user_id_b8110e_idx')],
            },
        ),
    ]
